### ISSUE TITLE
Possibility to link to a specific shade

### ISSUE THREAD

**Issue by Svish** [anheric/tailwindshades#14]
Would be very helpful to be able to link to a specific shade "setup". Just need 4 parameters really: The color, the two steps, and the name of the color.

Something like this:

    https://www.tailwindshades.com/?color=4B207F&up=15&down=5&name=foobar

Would be really nice when collaborating with others, as well as for documenting where the shade "setup" came from so it's possible to go back and re-adjust.

**Comment by leoquack** [comment]
That's a nice idea! Let me see if we can constantly change the URL parameters as we move the sliders, without any unintended consequences. Otherwise, a button to copy this "share" link can be added

**Comment by Svish** [comment]
A share link is probably good to have either way. I've experienced some issues with the typescript playground "auto url" not always being up-to-date, which is kind of annoying, so having an explicit "give me a URL for the current state"-button is great.

If you do make the URL parameters change, maybe you can use `replace` rather than `push`, to not create a browser history horribly long. Or maybe a combination somehow. Not sure what's best. Should most definitely be debounced/throttled somehow though.

**Comment by leoquack** [comment]
Yes from a very short research I found that a hashtag replace might work better but will stick to the button if it becomes too involved, I mean the upside of being able to copy the URL at anytime is small to begin with.

**Comment by Svish** [comment]
Simple is usually good. Easier to maintain, easier to deal with. 👍

**Comment by Svish** [comment]
Just tested it out, and it works great! 🙏
