### ISSUE TITLE
Define position of base color

### ISSUE THREAD

**Issue by smetzdev** [anheric/tailwindshades#22]
Hey there, really great tool!

It would be very cool if would be able to change the position of base color inside the array. 
Like for example if i have a really dark base color, it would make sense for it to be positioned on position 800.

In terms of UX it would be really nice if im able to drag and drop the position of the base color. 
Let me know if you are interested in implementing this and i maybe can help.

**Comment by leoquack** [comment]
Hi there, thanks for dropping by! Always cool to see people using the tool

I like the idea, we can test a few cases and see if the current shading algorithm works ok with other base positions.
Will certainly have a look when I get some free time, any help would be appreciated :)

**Comment by smetzdev** [comment]
Would be cool!

Just had a look over the code, sadly i don't know Vue. But with a little explanation i probably could help with the algorithm.

You got mentioned on the [COMPRESSEDfm](https://www.compressed.fm/) Podcast, thats why i've checked the page out:D
