### ISSUE TITLE
Add the ability to see and copy JSON snippet

### ISSUE THREAD

**Issue by simensen** [anheric/tailwindshades#43]
I'd be interested in having the ability to see and copy the color information as a JSON-compatible snippet in addition to the existing JavaScript snippet.

My use case is for tooling around colors that involve reading and consuming something like `colors.json` in some parts of the application but could also be used to inject as parsed JSON into `tailwind.config.js`.

Right now I'm doing this in my `tailwind.config.js`:

```javascript
const colors = require('../branding/colors.js')

const fs = require('fs');

fs.writeFileSync('../branding/colors.json', JSON.stringify(colors));

module.exports = {
  theme: {
    extend: {
      colors,
    },
  },
}
```

Which is fine, but it would be nicer if I could maintain `colors.json` instead of `colors.js` and not have an extra build step required to get `colors.json` to exist.

```javascript
const colors = require('../branding/colors.json')

module.exports = {
  theme: {
    extend: {
      colors,
    },
  },
}
```

Is this something you'd consider adding or supporting if I sent a PR?

**Comment by leoquack** [comment]
I would argue that converting JS to valid JSON is kinda trivial :D But it could definitely be included. Maybe in a dropdown option under the copy button, just like "save as new" is currently for shades? If you have something better in mind, let me know

![image](https://user-images.githubusercontent.com/2177500/184977318-88715048-bb76-47d2-8ecb-c6e730411726.png)

**Comment by simensen** [comment]
I think I'll leave this one for now. :) I don't have enough time to figure out how to do this and I already have a workaround. Thanks for merging #44. That is the main thing that will make my life easier. :)

**Comment by leoquack** [comment]
Sure thing! Thanks for the contribution :)
