### ISSUE TITLE
Specify stops

### ISSUE THREAD

**Issue by wrabit** [anheric/tailwindshades#6]
Would be cool to add stops i.e. 50, 100, 150, 200...

Great tool!

**Comment by leoquack** [comment]
That's a great idea! It didn't cross my mind - I never had "in-between" shades like 50, 150 in my projects
Thanks for sharing, I'll give it a shot sometime

**Comment by wrabit** [comment]
@anheric I notice another tool simply adds a single additional 50 before the 100. It's good because some shades you want a real light bg but the required weight varies from colour to colour to achieve this uniform lightness. Just something minor but would make the tool even more awesome. Probably a simple "[ ] Add more stops" checkbox which automatically creates 10 more.
