### ISSUE TITLE
Saved palette does not save base-stop correctly and wizard does not take base-stop parameter into account either

### ISSUE THREAD

**Issue by RyanTT** [anheric/tailwindshades#60]
Hi!

Loving the tool, however I have a minor issue:

When saving a color palette, die base stop always defaults to 5, even if I configured it to be something different before hitting the save button. Also: When loading a palette via an URL like https://www.tailwindshades.com/#color=0%2C0%2C9.411764705882353&step-up=2&step-down=11&hue-shift=0&name=cod-gray&base-stop=9&overrides=e30%3D the base-stop parameter with value 9 is not respected and it jumps back to 5.

Is this a me issue or an actual bug?

Thanks!

**Comment by leoquack** [comment]
Hi! Apologies for the late reply. Definitely a bug, but should be an easy fix - will have a look

**Comment by alexcroox** [comment]
The get code section also does not update if you change the uniform shades section values

**Comment by leoquack** [comment]
Thanks @alexcroox, will look into it asap, a page refresh fixes it alternatively for now
