### ISSUE TITLE
move base stop doesn't works in home page

### ISSUE THREAD

**Issue by buncis** [anheric/tailwindshades#73]
Because I cannot click it to change the value

![image](https://user-images.githubusercontent.com/14258779/226110915-e1a8b339-9715-4ab8-9c32-25d6364b6199.png)

**Comment by buncis** [comment]
seems not, it should be clickable because after I click shade I could change the value there

![image](https://user-images.githubusercontent.com/14258779/226111103-e1a3ba66-c93c-47cc-afb6-cc488e7c4de1.png)

**Comment by leoquack** [comment]
Oh wow, I did not notice that was broken this whole time

Will fix in a few minutes, thanks!
