### ISSUE TITLE
Support for 950 stop

### ISSUE THREAD

**Issue by brc-dd** [anheric/tailwindshades#74]
Tailwind CSS has recently added 950 as a stop too: https://tailwindcss.com/blog/tailwindcss-v3-3#extended-color-palette-for-darker-darks

Can we have that here too alongside 900?

**Comment by leoquack** [comment]
The code required to add this is very little, however, I will have to make it compatible with already saved shades.

**Comment by leoquack** [comment]
Done. Hopefully I didn't break everyone's shades!
