### ISSUE TITLE
Base color not the same

### ISSUE THREAD

**Issue by KevinBatdorf** [anheric/tailwindshades#8]
Easier to show with a gif. I entered `#285e97` and it converted it to `#285d95`

![wrongcolor](https://user-images.githubusercontent.com/1478421/101982912-bcd2c000-3ca9-11eb-913a-e3f708bedc0e.gif)

**Comment by leoquack** [comment]
Some loss in the conversion must be going on, from hex to hsl.
Thanks! I'll look into it
